export const mockData = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    status: "Active",
    lastActive: "Just now",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "User",
    status: "Active",
    lastActive: "5 minutes ago",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    role: "Editor",
    status: "Idle",
    lastActive: "1 hour ago",
  },
  {
    id: "4",
    name: "Alice Williams",
    email: "alice.williams@example.com",
    role: "User",
    status: "Offline",
    lastActive: "1 day ago",
  },
  {
    id: "5",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    role: "Viewer",
    status: "Active",
    lastActive: "30 minutes ago",
  },
  {
    id: "6",
    name: "Diana Prince",
    email: "diana.prince@example.com",
    role: "Admin",
    status: "Idle",
    lastActive: "45 minutes ago",
  },
  {
    id: "7",
    name: "Edward Norton",
    email: "edward.norton@example.com",
    role: "Editor",
    status: "Offline",
    lastActive: "3 days ago",
  },
  {
    id: "8",
    name: "Fiona Apple",
    email: "fiona.apple@example.com",
    role: "User",
    status: "Active",
    lastActive: "10 minutes ago",
  },
  {
    id: "9",
    name: "George Lucas",
    email: "george.lucas@example.com",
    role: "Viewer",
    status: "Active",
    lastActive: "2 hours ago",
  },
  {
    id: "10",
    name: "Helen Hunt",
    email: "helen.hunt@example.com",
    role: "User",
    status: "Offline",
    lastActive: "1 week ago",
  },
  {
    id: "11",
    name: "Ian McKellen",
    email: "ian.mckellen@example.com",
    role: "Admin",
    status: "Active",
    lastActive: "15 minutes ago",
  },
  {
    id: "12",
    name: "Julia Roberts",
    email: "julia.roberts@example.com",
    role: "Editor",
    status: "Idle",
    lastActive: "3 hours ago",
  },
]

